FROM mariadb:10.5.8-focal

# Add the main user with specific UID
ARG USER=mysql
ARG UID=2000
RUN sed -i -e "s/^\($USER:[^:]\):[0-9]*:[0-9]*:/\1:$UID:$UID:/" /etc/passwd && \
	sed -i -e "s/^\($USER:[^:]\):[0-9]*:/\1:$UID:/" /etc/group
